---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Categórica, Categórica, Ordinal, Discreta
  checked: false
- value: Continua, Ordinal, Discreta,  Discreta
  checked: false
- value: Ordinal, Categórica, Continua, Continua
  checked: true
- value: Continua, Discreta, Discreta, Continua
  checked: false
name: Tipos de variables
