---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Categórica, Categórica, Ordinal, Discreta
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Continua, Ordinal, Discreta,  Discreta
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ordinal, Categórica, Continua, Continua
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Continua, Discreta, Discreta, Continua
  checked: false
name: Tipos de variables
