---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '38.22'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '36.33'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '35.22'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '37.23'
  checked: false
name: Media
