---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '42'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '40.5'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '39.75'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '43.5'
  checked: false
name: Mediana
