---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '38'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '40.5'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '42.3'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '43.5'
  checked: true
name: Mediana
